Company.G03.PL/Controllers/DepartmentController.cs
using AutoMapper;
using Company.G03.BLL.Interfaces;
using Company.G03.DAL.Data.Contexts;
using Company.G03.DAL.Models;
using Company.G03.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.G03.PL.Controllers
{
    [Authorize]
    public class DepartmentController : Controller
    {
        #region Get a Repository object
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public DepartmentController(IUnitOfWork unitOfWork,IMapper mapper) // Ask Clr to create object from departmentRepository
        {
            //_departmentRepository = departmentRepository;
           _unitOfWork = unitOfWork;
            _mapper = mapper;
        }
        #endregion

        #region Index
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var department = await _unitOfWork.Department.GetAllAsync();

          //var departmentViewModel =  _mapper.Map<DepartmentViewModel>(department);
            return View(department);
        }
        #endregion

        #region Create
        [HttpGet]
        public IActionResult Create()
        {


            return View();
        }
        //-----------------------------------------------------------*
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Department model)
        {
            if (ModelState.IsValid)
            {

                 await _unitOfWork.Department.AddAsync(model);
                var Count = await _unitOfWork.CompleteAsync();
                if (Count > 0)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(model);
        }

        #endregion


        #region Details

        public async Task<IActionResult> Details(int? id, string ViewName = "Details")
        {
            if (id == null)
            {
                return BadRequest(); //400
            }
            var department = await _unitOfWork.Department.GetAsync(id.Value);

            if (department == null)
            {
                return NotFound(); //404
            }
            return View(ViewName, department);
        }
        #endregion

        #region Edit
        [HttpGet]
        public async Task<IActionResult> Edit(int? id) => await Details(id, "Edit");


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id, Department model)
        {
            try
            {
                if (id != model.Id)
                {
                    return BadRequest();
                }
                if (ModelState.IsValid)
                {
                    _unitOfWork.Department.Update(model);
                    var Count = await _unitOfWork.CompleteAsync();
                    if (Count > 0)
                    {
                        return RedirectToAction("Index");
                    }
                }

            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(model);
        }
        #endregion

        //----------------------------------------------------------

        #region Delete
        [HttpGet]
        public async Task<IActionResult> Delete(int? id) => await Details(id, "Delete");

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] int? id, Department entity)
        {
            try
            {
                if (id != entity.Id)
                {
                    return BadRequest();
                }
                if (ModelState.IsValid)
                {
                    _unitOfWork.Department.Delete(entity); //Delegate but not now
                    var Count = await _unitOfWork.CompleteAsync();
                    if (Count > 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }

                }
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
            }
            return View(entity);
        }
        #endregion

    }
}

Company.G03.PL/Controllers/RoleController.cs
using Company.G03.DAL.Models;
using Company.G03.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Company.G03.PL.Controllers
{
    [Authorize(Roles ="Admin")]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager, UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string searchInput)
        {

            var roles = Enumerable.Empty<RoleViewModel>();

            if (string.IsNullOrEmpty(searchInput))
            {
                roles = await _roleManager.Roles.Select(r => new RoleViewModel()
                {
                    Id = r.Id,
                    RoleName = r.Name
                }).ToListAsync();
            }
            else
            {
                roles = await _roleManager.Roles.Where(r => r.Name
                                     .ToLower()
                                     .Contains(searchInput.ToLower()))
                                     .Select(r => new RoleViewModel()
                                     {
                                         Id = r.Id,
                                         RoleName = r.Name
                                     }).ToListAsync();
            }
            return View(roles);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var RoleById = await _roleManager.FindByIdAsync(model.Id);
                if (RoleById is null)
                {
                    var Role = new IdentityRole()
                    {
                        Name = model.RoleName
                    };
                    var Result = await _roleManager.CreateAsync(Role);
                    if (Result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            ModelState.AddModelError(string.Empty, "Invalid model");
            return View(model);
        }


        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            try
            {

                if (id is null)
                {
                    return BadRequest();
                }
                var roleFromDb = await _roleManager.FindByIdAsync(id);
                if (roleFromDb is null)
                {
                    return NotFound();
                }
                var role = new RoleViewModel()
                {
                    Id = roleFromDb.Id,
                    RoleName = roleFromDb.Name
                };
                return View(ViewName, role);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }

        }


        [HttpGet]
        public async Task<IActionResult> Edit(string? id) => await Details(id, "Edit");


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel model)
        {
            if (id != model.Id)
            {
                return BadRequest();
            }
            try
            {

                if (ModelState.IsValid)
                {
                    var roleFromDb = await _roleManager.FindByIdAsync(id);
                    if (roleFromDb is null)
                    {
                        return NotFound();
                    }
                    //applying and mapping edits
                    roleFromDb.Name = model.RoleName;

                    //the Update method
                    var result = await _roleManager.UpdateAsync(roleFromDb);
                    if (result.Succeeded)
                    {

                        return RedirectToAction(nameof(Index));
                    }
                    ModelState.AddModelError(string.Empty, "Invalid Operation");
                }

            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);

            }
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Delete(string? id) => await Details(id, "Delete");

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete([FromRoute] string? id, RoleViewModel model)
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {
                //finding the role
                var roleFromDb = await _roleManager.FindByIdAsync(id);

                if (roleFromDb is null)
                    return NotFound();
                else
                {
                    //Deleting the role
                    await _roleManager.DeleteAsync(roleFromDb);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }


        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {

            var role = await _roleManager.FindByIdAsync(roleId);

            if (role is null)
                return NotFound();

            ViewData["roleId"] = roleId;

            var usersInRole = new List<UsersInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();

            foreach (var user in users)
            {
                var userInRole = new UsersInRoleViewModel()
                {
                    UserId = user.Id,
                    UserName = user.UserName
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userInRole.IsSelected = true;

                }
                else
                {
                    userInRole.IsSelected = false;
                }
                usersInRole.Add(userInRole);
            }

            return View(usersInRole);
        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId, List<UsersInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);

            if (role is null)
                return NotFound();


            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appUser = await _userManager.FindByIdAsync(user.UserId);
                    if(appUser is not null)
                    {
                        if (user.IsSelected && !await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.AddToRoleAsync(appUser, role.Name);
                        }
                        else if (!user.IsSelected && await _userManager.IsInRoleAsync(appUser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appUser, role.Name);
                        }
                    }
                }
                return RedirectToAction(nameof(Edit), new {id = roleId});
            }
            return View(users);
        }

    }
}

Company.G03.PL/Controllers/UserController.cs
using Company.G03.DAL.Models;
using Company.G03.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace Company.G03.PL.Controllers
{
    [Authorize(Roles="Admin")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserController(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }
        public async Task<IActionResult> Index(string searchInput)
        {

            var users = Enumerable.Empty<UserViewModel>();

            if (string.IsNullOrEmpty(searchInput))
            {
                users = await _userManager.Users.Select(u => new UserViewModel()
                {
                    Id = u.Id,
                    FirstName = u.FirstName,
                    LastName = u.LastName,
                    Email = u.Email,
                    Roles = _userManager.GetRolesAsync(u).GetAwaiter().GetResult()
                }).ToListAsync();
            }
            else
            {
                users = await _userManager.Users.Where(u => u.Email
                                     .ToLower()
                                     .Contains(searchInput.ToLower()))
                                     .Select(u => new UserViewModel()
                                     {
                                         Id = u.Id,
                                         FirstName = u.FirstName,
                                         LastName = u.LastName,
                                         Email = u.Email,
                                         Roles = _userManager.GetRolesAsync(u).GetAwaiter().GetResult()
                                     }).ToListAsync();
            }
            return View(users);
        }


        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {
            try
            {

                if (id is null)
                {
                    return BadRequest();
                }
                var userFromDb = await _userManager.FindByIdAsync(id);
                if (userFromDb is null)
                {
                    return NotFound();
                }
                var user = new UserViewModel()
                {
                    Id = userFromDb.Id,
                    FirstName = userFromDb.FirstName,
                    LastName = userFromDb.LastName,
                    Email = userFromDb.Email,
                    Roles = _userManager.GetRolesAsync(userFromDb).GetAwaiter().GetResult()
                };
                return View(ViewName, user);
            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);
                return RedirectToAction("Error", "Home");
            }

        }
        [HttpGet]
        public async Task<IActionResult> Edit(string? id) => await Details(id, "Edit");


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel model)
        {
            if (id != model.Id)
            {
                return BadRequest();
            }
            try
            {

                if (ModelState.IsValid)
                {
                    var userFromDb = await _userManager.FindByIdAsync(id);
                    if (userFromDb is null)
                    {
                        return NotFound();
                    }
                    userFromDb.FirstName = model.FirstName;
                    userFromDb.LastName = model.LastName;
                    userFromDb.Email = model.Email;

                    var result = await _userManager.UpdateAsync(userFromDb);
                    if (result.Succeeded)
                    {

                        return RedirectToAction(nameof(Index));
                    }
                    ModelState.AddModelError(string.Empty, "Invalid Operation");
                }

            }
            catch (Exception ex)
            {

                ModelState.AddModelError(string.Empty, ex.Message);

            }
            return View(model);
        }
        [HttpGet]
        public async Task<IActionResult> Delete(string? id) => await Details(id, "Delete");
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string? id, UserViewModel model)
        {
            if (id != model.Id) return BadRequest();

            if (ModelState.IsValid)
            {
                var userFromDb = await _userManager.FindByIdAsync(id);
                if (userFromDb is null) return NotFound();
                else
                {
                    await _userManager.DeleteAsync(userFromDb);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }


    }
}

Company.G03.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="~/css/Auth.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative SignUp Form</h1>
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

Company.G03.PL/Views/Shared/_ButtonPartialView.cshtml
@model string
<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-success">
        <img src="~/images/information_icon.png"  alt="Alternate Text" />
        
    </a>

</td>
<td>
    <a asp-action="Edit" asp-route-id="@Model" class=" btn btn-warning">
        <img src="~/images/pencil_edit_icon.png"  alt="Alternate Text" />
        
    </a>

</td>
<td>

    <a asp-action="Delete" asp-route-id="@Model" class=" btn btn-danger">
        <img src="~/images/delete_icon.png" alt="Alternate Text" />

       </a>
</td>

Company.G03.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.G03.PL</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.G03.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark" style="color:white;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.G03.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="User" asp-action="Index">User</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Role" asp-action="Index">Role</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav ">
                        <li class="nav-item  ">
                            <a class="nav-link text-dark btn btn-warning" style="background-color:#cf850f; margin-right:10px;" asp-controller="Account" asp-action="SignOut">
                                LogOut
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.G03.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Validation", required: false)
</body>
</html>